# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Salik Syed
"""Reference Generator implementation — NOT registered by default.

This distribution ships no generators (see
`app/pipeline/execution/registry.py`). This file exists so the extension point
is learnable: it is the smallest complete generator, deliberately deterministic
so you can read what the interface requires without an LLM call in the way.

To use it, either register it in-process:

    from app.pipeline.execution.registry import register_generator
    from examples.generators.robots_txt import RobotsTxtFixer

    register_generator(RobotsTxtFixer())

or ship it from your own package via the entry point:

    [project.entry-points."geo.generators"]
    robots_txt = "mypkg.robots_txt:RobotsTxtFixer"

Either way the execution stage picks it up with no changes to this repo.

What a generator owes the pipeline:
  * `fix_type`  — matches the fix_type the planner emits for a gap_type
                  (see config/gap_taxonomy.yaml and config/planner.yaml)
  * `asset_type`— the label recorded on the produced assets row
  * `generate(item, context) -> AssetDraft`

What the pipeline owes the generator: the context it receives has ALREADY been
through `facts_gate.sanitize_context`, so unfilled placeholder facts are gone
before you see them. Any claim you declare on the draft is checked against
`verified_facts` by `validate.finalize_asset`, and an unbacked claim about the
customer or a named competitor rejects the asset. Both of those live in the open
repo precisely because a third-party generator needs them.
"""

from __future__ import annotations

from app.pipeline.diagnosis.config import get_bot_registry
from app.pipeline.execution.base import Generator
from app.pipeline.execution.contracts import AssetDraft, GeneratorContext, PlanItem


class RobotsTxtFixer(Generator):
    """Emit a corrected robots.txt that explicitly allows every citation-time
    SEARCH bot listed in config/ai_bots.yaml. Deterministic — no LLM, and no
    claims, so it has nothing to verify against verified_facts."""

    fix_type = "fix_robots_txt"
    asset_type = "robots_txt"

    def generate(self, item: PlanItem, context: GeneratorContext) -> AssetDraft:
        search_bots = [b for b in get_bot_registry().bots if b.category == "search"]
        lines = [
            "# Corrected robots.txt — explicitly allow AI search/citation bots.",
            "# Generated by GEO; review before publishing.",
            "",
        ]
        for bot in search_bots:
            lines += [f"User-agent: {bot.token}", "Allow: /", ""]
        lines += ["User-agent: *", "Disallow:", ""]
        return AssetDraft(
            asset_type=self.asset_type,
            fix_type=self.fix_type,
            title="Corrected robots.txt (allow AI search bots)",
            content="\n".join(lines),
            content_kind="text",
            target_prompt_ids=context.target_prompt_ids,
        )
