"""RobotsTxtFixer: emit a corrected robots.txt that explicitly allows every
citation-time SEARCH bot (from config/ai_bots.yaml). Deterministic — no LLM."""

from __future__ import annotations

from app.pipeline.diagnosis.config import get_bot_registry
from app.pipeline.execution.base import Generator
from app.pipeline.execution.contracts import AssetDraft, GeneratorContext, PlanItem


class RobotsTxtFixer(Generator):
    fix_type = "fix_robots_txt"
    asset_type = "robots_txt"

    def generate(self, item: PlanItem, context: GeneratorContext) -> AssetDraft:
        search_bots = [b for b in get_bot_registry().bots if b.category == "search"]
        lines = [
            "# Corrected robots.txt — explicitly allow AI search/citation bots.",
            "# Generated by GEO; review before publishing.",
            "",
        ]
        for bot in search_bots:
            lines += [f"User-agent: {bot.token}", "Allow: /", ""]
        lines += ["User-agent: *", "Disallow:", ""]
        return AssetDraft(
            asset_type=self.asset_type,
            fix_type=self.fix_type,
            title="Corrected robots.txt (allow AI search bots)",
            content="\n".join(lines),
            content_kind="text",
            target_prompt_ids=context.target_prompt_ids,
        )
